import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";
import "bootstrap/dist/css/bootstrap.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import { Col, Container, Row } from "reactstrap";
import { useEffect, useState } from "react";

const CounterDisplay = dynamic(() => import("./components/CounterDisplay"));
const CounterButtons = dynamic(() => import("./components/CounterButtons"));
const HomeSlider = dynamic(() => import("./components/HomeSlider"));
const HomePage = dynamic(() => import("./components/HomePage"));
const Header = dynamic(() => import("./components/Header"));
const TextContent = dynamic(() => import("./components/TextContent"));
const TagsAndShare = dynamic(() => import("./components/TagsAndShare"));
const CardList = dynamic(() => import("./components/CardList"));
const Comments = dynamic(() => import("./components/Comments"));
const Footer = dynamic(() => import("./components/Footer"));
const HomeSimpleSlider = dynamic(() => import("./components/HomeSimpleSlider"));

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const [windowWidth, setWindowWidth] = useState(0);

  useEffect(() => {
    const handleResize = () => {
      setWindowWidth(window.innerWidth);
    };

    window.addEventListener("resize", handleResize);
    handleResize(); // Set initial value

    return () => window.removeEventListener("resize", handleResize);
  }, []);

  return (
    <>
      <Head>
        <title>Crypto UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Container fluid>
          <Row className="mt-2">
            {/* Reverse order for mobile screens */}
            <Col
              className="d-flex order-2 order-md-1 mt-3 mt-lg-0"
              sm="12"
              xs="12"
              md="12"
              lg="3"
            >
              <HomePage />
            </Col>
            <Col className="order-1 order-md-2 " sm="12" xs="12" md="12" lg="9">
              {windowWidth <= 1024 ? <HomeSimpleSlider /> : <HomeSlider />}
            </Col>
          </Row>
          <Row className="mt-5">
            <Header />
            <hr style={{ border: "1px solid #ccc", marginBottom: "20px" }} />
          </Row>
          <Row id="1" className=" mt-5">
            {/* Reverse order for mobile screens */}
            <Col
              className="d-flex order-2 order-md-1 vh-90"
              sm="12"
              xs="12"
              md="9"
            >
              <TextContent />
            </Col>
            <Col className="order-1 order-md-2 vh-90" sm="12" xs="12" md="3">
              <TagsAndShare />
            </Col>
          </Row>
          <Row id="2" className=" mt-5">
            {/* Reverse order for mobile screens */}
            <Col sm="12" xs="12" md="9">
              <Comments />
            </Col>
            <Col sm="12" xs="12" md="3">
              <div className="details mt-3">
                <p style={{ margin: 0 }}>Last updated 2 months ago</p>
                <p style={{ margin: 0 }}>
                  Support:{" "}
                  <a
                    href="mailto:support@designluch.com"
                    style={{ color: "#007bff", textDecoration: "none" }}
                  >
                    support@designluch.com
                  </a>
                </p>
                <p style={{ margin: 0 }}>
                  Licensed under{" "}
                  <a
                    href="#"
                    style={{ color: "#007bff", textDecoration: "none" }}
                  >
                    Community Paid Resource License
                  </a>
                </p>
              </div>
              <hr style={{ margin: "20px 0", borderColor: "#d3d3d3" }} />
              {/* Report Resource Link */}
              <div className="report-resource mt-3">
                <a
                  href="#"
                  style={{
                    color: "gray",
                    textDecoration: "none",
                    fontSize: "14px",
                  }}
                >
                  Report resource
                </a>
              </div>
            </Col>
          </Row>
        </Container>
      </main>
      <Footer />
    </>
  );
}
